package webservice;

public class MainWebService{

        private final long id;
        private final PostNew content;

        public MainWebService(PostNew content) {
            this.id = 1L;//autogenerated
            this.content = content;
        }

        public long getId() {
            return id;
        }

        public PostNew getContent() {
            return content;
        }
}